// <auto-generated />
using System;
using GraduationProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduationProject.Migrations
{
    [DbContext(typeof(GraduationDbContext))]
    [Migration("20240121160238_SomeRelations")]
    partial class SomeRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraduationProject.Models.Hospital_Admin", b =>
                {
                    b.Property<string>("AdminSsn")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("AdminBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdminCity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdminPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("AdminStreet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AdminZipCode")
                        .HasColumnType("int");

                    b.HasKey("AdminSsn");

                    b.ToTable("hospital_Admins");
                });

            modelBuilder.Entity("GraduationProject.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<DateTime>("MedicineExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MedicineIsAvailable")
                        .HasMaxLength(5)
                        .HasColumnType("bit");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("GraduationProject.Models.Patient", b =>
                {
                    b.Property<string>("PatientSsn")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("AdminSsn")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("MangedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PatientBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientCity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PatientStreet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PatientZipCode")
                        .HasColumnType("int");

                    b.HasKey("PatientSsn");

                    b.HasIndex("AdminSsn");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("GraduationProject.Models.Relative", b =>
                {
                    b.Property<int>("RelativeSsn")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(14)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelativeSsn"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdminSsn")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("DegreeOfKinShip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RelativeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RelativePhone")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.HasKey("RelativeSsn");

                    b.HasIndex("AdminSsn");

                    b.ToTable("relatives");
                });

            modelBuilder.Entity("GraduationProject.Models.RelativeMedicine", b =>
                {
                    b.Property<int>("RelativeSsn")
                        .HasColumnType("int");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.HasKey("RelativeSsn", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("RelativeMedicine");
                });

            modelBuilder.Entity("MedicineRelative", b =>
                {
                    b.Property<int>("MedicinesMedicineId")
                        .HasColumnType("int");

                    b.Property<int>("RelativeSsn")
                        .HasColumnType("int");

                    b.HasKey("MedicinesMedicineId", "RelativeSsn");

                    b.HasIndex("RelativeSsn");

                    b.ToTable("MedicineRelative");
                });

            modelBuilder.Entity("GraduationProject.Models.Patient", b =>
                {
                    b.HasOne("GraduationProject.Models.Hospital_Admin", "hospital_Admins")
                        .WithMany("patients")
                        .HasForeignKey("AdminSsn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hospital_Admins");
                });

            modelBuilder.Entity("GraduationProject.Models.Relative", b =>
                {
                    b.HasOne("GraduationProject.Models.Hospital_Admin", "hospital_Admins")
                        .WithMany("relatives")
                        .HasForeignKey("AdminSsn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hospital_Admins");
                });

            modelBuilder.Entity("GraduationProject.Models.RelativeMedicine", b =>
                {
                    b.HasOne("GraduationProject.Models.Medicine", "medicine")
                        .WithMany("RelativeMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraduationProject.Models.Relative", "Relative")
                        .WithMany("RelativeMedicines")
                        .HasForeignKey("RelativeSsn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relative");

                    b.Navigation("medicine");
                });

            modelBuilder.Entity("MedicineRelative", b =>
                {
                    b.HasOne("GraduationProject.Models.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicinesMedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraduationProject.Models.Relative", null)
                        .WithMany()
                        .HasForeignKey("RelativeSsn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GraduationProject.Models.Hospital_Admin", b =>
                {
                    b.Navigation("patients");

                    b.Navigation("relatives");
                });

            modelBuilder.Entity("GraduationProject.Models.Medicine", b =>
                {
                    b.Navigation("RelativeMedicines");
                });

            modelBuilder.Entity("GraduationProject.Models.Relative", b =>
                {
                    b.Navigation("RelativeMedicines");
                });
#pragma warning restore 612, 618
        }
    }
}
